export const LOCALIZATION = {
  en: {
    // Navigation & Tabs
    dashboard: "Dashboard",
    lessons: "Lessons",
    speed_test: "Speed Test",
    games: "Arcade",
    settings: "Settings",
    logs: "Logs",
    leaderboard: "Leaderboard",
    back_to_menu: "Back to Menu",

    // Dashboard metrics
    streak: "Daily Streak",
    coins: "Coins",
    level: "Level",
    xp: "XP Progress",
    best_wpm: "PB Speed",
    rank: "Pilot Rank",
    continue_lesson: "Resume Lesson",
    start_test: "Launch Test",
    welcome_pilot: "Welcome, Pilot",
    weak_keys: "Weak Keys",
    correct_keys: "Proficient Keys",
    recent_activity: "Recent Activity",

    // Settings
    identity_config: "Pilot Identity Config",
    update_username: "Update Username",
    deep_synth: "Keyboard Deep Synth",
    sound_status: "Synthesized Clicker",
    sound_presets: "Active Sound Profile",
    volume: "Volume Control",
    sound_enabled: "SFX Enabled",
    sound_disabled: "SFX Muted",
    bgm_title: "Focus Flow Ambient BGM",
    bgm_enabled: "BGM Active",
    bgm_disabled: "BGM Muted",
    theme_selection: "Accent Hue & Style",
    bright_mode: "Bright Interface",
    dark_mode: "Cyberpunk Dark Mode",
    primary_color: "Theme Primary Accent",
    font_size_title: "Workspace Font Sizing",
    system_specs: "Service Engine Specs",
    reminder_title: "Daily Practice Reminders",
    reminder_time_label: "Scheduled Alert Time",
    test_push_btn: "Trigger Test Notification",
    language_title: "System Localization",
    specs_desc: "TypeMaster Pro v3.8 — Running synthesized FM oscillator frequency circuits, high accuracy local storage state vectors, and secure proxy interfaces.",

    // Core Typing Actions
    current_passage: "Active Passage Selection",
    time_limit: "Test Time Limit",
    sec_unit: "seconds",
    custom_time: "Custom Interval",
    start_run: "Engage Keystroke Session",
    speed: "Speed",
    accuracy: "Accuracy",
    mistakes: "Mistakes",
    progress: "Progress",
    target: "Target",
    xp_rewards: "XP Reward Gained",
    coins_gained: "Coins Reward Gained",
    perfect_run: "Perfect Accuracy Bonus!",
    new_personal_best: "New Personal Best!",
    results_summary: "Keystroke Session Results",
    try_again: "Retry Session",

    // Arcade Game Screen
    falling_words: "Falling Words",
    space_shooter: "Typing Space Combat",
    arcade_play: "Play",
    arcade_high: "High Score",
    score: "Score",
    game_over: "Game Over",
    wave: "Wave",
    coins_earned: "Coins Earned",
    start_game: "Initialize Game",
    type_to_shoot: "Type the words to play!"
  },
  es: {
    // Navigation & Tabs
    dashboard: "Tablero",
    lessons: "Lecciones",
    speed_test: "Prueba WPM",
    games: "Arcade",
    settings: "Ajustes",
    logs: "Registros",
    leaderboard: "Clasificación",
    back_to_menu: "Menu Principal",

    // Dashboard metrics
    streak: "Racha Diaria",
    coins: "Monedas",
    level: "Nivel",
    xp: "Progreso XP",
    best_wpm: "Récord WPM",
    rank: "Rango de Piloto",
    continue_lesson: "Reanudar Lección",
    start_test: "Iniciar Prueba",
    welcome_pilot: "Bienvenido, Piloto",
    weak_keys: "Teclas Débiles",
    correct_keys: "Teclas Dominadas",
    recent_activity: "Actividad Reciente",

    // Settings
    identity_config: "Configuración de Piloto",
    update_username: "Cambiar Nombre",
    deep_synth: "Sintetizador de Teclado",
    sound_status: "Gatillo de Sonido",
    sound_presets: "Perfil Acústico",
    volume: "Regulador de Volumen",
    sound_enabled: "Efectos Activos",
    sound_disabled: "Efectos Mudos",
    bgm_title: "Música de Fondo Relajante",
    bgm_enabled: "Música Activa",
    bgm_disabled: "Música Muda",
    theme_selection: "Tonalidad y Estéticas",
    bright_mode: "Interfaz Clara",
    dark_mode: "Oscuro Cyberpunk",
    primary_color: "Acento de Color Primario",
    font_size_title: "Tamaño de Texto",
    system_specs: "Especificaciones de Motor",
    reminder_title: "Recordatorio de Práctica",
    reminder_time_label: "Hora de Alerta Programada",
    test_push_btn: "Probar Notificación Push",
    language_title: "Idioma de Interfaz",
    specs_desc: "TypeMaster Pro v3.8 — Ejecutando circuitos de sintetizador FM de baja latencia, persistencia local segura y API de canal ágil.",

    // Core Typing Actions
    current_passage: "Pasaje de Texto Seleccionado",
    time_limit: "Límite de Tiempo de Prueba",
    sec_unit: "segundos",
    custom_time: "Intervalo Personalizado",
    start_run: "Iniciar Sesión de Escritura",
    speed: "Velocidad",
    accuracy: "Precisión",
    mistakes: "Errores",
    progress: "Progreso",
    target: "Objetivo",
    xp_rewards: "XP Obtenida",
    coins_gained: "Monedas Ganadas",
    perfect_run: "Bono de Precisión Perfecta!",
    new_personal_best: "¡Nuevo Récord Personal!",
    results_summary: "Resumen de Sesión de Teclado",
    try_again: "Repetir Sesión",

    // Arcade Game Screen
    falling_words: "Palabras Descendientes",
    space_shooter: "Combate de Caza Espacial",
    arcade_play: "Jugar",
    arcade_high: "Récord",
    score: "Puntos",
    game_over: "Fin del Juego",
    wave: "Oleada",
    coins_earned: "Monedas Ganadas",
    start_game: "Inicializar Combate",
    type_to_shoot: "¡Escribe palabras para disparar!"
  },
  fr: {
    // Navigation & Tabs
    dashboard: "Tableau",
    lessons: "Leçons",
    speed_test: "Test WPM",
    games: "Arcade",
    settings: "Réglages",
    logs: "Analyses",
    leaderboard: "Classement",
    back_to_menu: "Menu Général",

    // Dashboard metrics
    streak: "Série du Jour",
    coins: "Pièces",
    level: "Niveau",
    xp: "Progression XP",
    best_wpm: "Record WPM",
    rank: "Rang Pilote",
    continue_lesson: "Continuer",
    start_test: "Lancer le Test",
    welcome_pilot: "Bienvenue, Pilote",
    weak_keys: "Touches Faibles",
    correct_keys: "Touches Maîtrisées",
    recent_activity: "Activité Récente",

    // Settings
    identity_config: "Profil de Pilote",
    update_username: "Mettre à jour",
    deep_synth: "Synthétiseur de Clavier",
    sound_status: "Clic de Touche",
    sound_presets: "Profil Acoustique",
    volume: "Contrôle du Volume",
    sound_enabled: "SFX Activé",
    sound_disabled: "SFX Coupé",
    bgm_title: "Ambiance Musicale Focus",
    bgm_enabled: "BGM Activée",
    bgm_disabled: "BGM Coupée",
    theme_selection: "Thèmes & Esthétique",
    bright_mode: "Interface Claire",
    dark_mode: "Mode Sombre Cyberpunk",
    primary_color: "Couleur d'Accent",
    font_size_title: "Taille de Police",
    system_specs: "Spécifications Système",
    reminder_title: "Rappels de Pratique",
    reminder_time_label: "Heure d'Alerte Prévue",
    test_push_btn: "Déclencher une Notification",
    language_title: "Langue de l'Option",
    specs_desc: "TypeMaster Pro v3.8 — Gérant des circuits d'oscillation de fréquence d'onde synthétisés, tampons locaux fiables et passerelle proxy sécurisée.",

    // Core Typing Actions
    current_passage: "Sélection du Texte",
    time_limit: "Temps Limite du Test",
    sec_unit: "secondes",
    custom_time: "Intervalle Personnalisé",
    start_run: "Lancer la Frappe",
    speed: "Vitesse",
    accuracy: "Précision",
    mistakes: "Erreurs",
    progress: "Progression",
    target: "Cible",
    xp_rewards: "Points XP Gagnés",
    coins_gained: "Pièces Gagnées",
    perfect_run: "Bonus Précision Parfaite!",
    new_personal_best: "Nouveau Record Personnel !",
    results_summary: "Bilan de la Session de Frappe",
    try_again: "Recommencer",

    // Arcade Game Screen
    falling_words: "Mots Chuteurs",
    space_shooter: "Combat Spatial de Dactylo",
    arcade_play: "Jouer",
    arcade_high: "Meilleur Score",
    score: "Score",
    game_over: "Fin de Partie",
    wave: "Vague",
    coins_earned: "Pièces Gagnées",
    start_game: "Initialiser Partie",
    type_to_shoot: "Saisissez les mots pour tirer !"
  },
  de: {
    // Navigation & Tabs
    dashboard: "Cockpit",
    lessons: "Lektionen",
    speed_test: "Tipp-Test",
    games: "Arcade",
    settings: "Optionen",
    logs: "Statistik",
    leaderboard: "Bestenliste",
    back_to_menu: "Hauptmenü",

    // Dashboard metrics
    streak: "Tägliche Serie",
    coins: "Münzen",
    level: "Stufe",
    xp: "XP Fortschritt",
    best_wpm: "Rekord-WPM",
    rank: "Pilotengrad",
    continue_lesson: "Fortsetzen",
    start_test: "Test Starten",
    welcome_pilot: "Kommando-Schnittstelle",
    weak_keys: "Defizitäre Tasten",
    correct_keys: "Meisterhafte Tasten",
    recent_activity: "Letzte Aktivitäten",

    // Settings
    identity_config: "Pilotenfunk-Rufname",
    update_username: "Aktualisieren",
    deep_synth: "Tastatur-Synthesizer",
    sound_status: "Dactylo Akustik",
    sound_presets: "Klangvoreinstellungen",
    volume: "Lautstärke-Regler",
    sound_enabled: "SFX Aktiviert",
    sound_disabled: "SFX Stummgeschaltet",
    bgm_title: "Focus Flow Hintergrundmusik",
    bgm_enabled: "BGM Aktiv",
    bgm_disabled: "BGM Stumm",
    theme_selection: "Farbschema & Design",
    bright_mode: "Helles Interface",
    dark_mode: "Cyberpunk Dunkelmodus",
    primary_color: "Primäre Akzentfarbe",
    font_size_title: "Schriftgröße-Display",
    system_specs: "System-Spezifikationen",
    reminder_title: "Tägliche Trainingsalarme",
    reminder_time_label: "Geplante Benachrichtigungszeit",
    test_push_btn: "Testbenachrichtigung auslösen",
    language_title: "Systemschnittstellen-Sprache",
    specs_desc: "TypeMaster Pro v3.8 — Getrieben von software-synthetisierten Frequenzgeneratoren, robusten Client-Speichern und lizenzierten Kernmodulen.",

    // Core Typing Actions
    current_passage: "Ausgewählter Absatz",
    time_limit: "Prüfungszeitlimit",
    sec_unit: "Sekunden",
    custom_time: "Alternatives Intervall",
    start_run: "Tastaturtest Starten",
    speed: "Tempo",
    accuracy: "Präzision",
    mistakes: "Fehler",
    progress: "Fortlauf",
    target: "Sollwert",
    xp_rewards: "Erhältliche XP",
    coins_gained: "Münzen-Belohnung",
    perfect_run: "Bonus für fehlerfreies Tippen!",
    new_personal_best: "Neue persönliche Bestleistung!",
    results_summary: "Leistungsbewertung",
    try_again: "Sitzung wiederholen",

    // Arcade Game Screen
    falling_words: "Fallende Begriffe",
    space_shooter: "Weltraum-Schreibkampf",
    arcade_play: "Spielen",
    arcade_high: "Highscore",
    score: "Punkte",
    game_over: "Spiel Vorbei",
    wave: "Welle",
    coins_earned: "Münzen Verdient",
    start_game: "Kampf starten",
    type_to_shoot: "Wörter tippen, um anzugreifen!"
  },
  ja: {
    // Navigation & Tabs
    dashboard: "ダッシュボード",
    lessons: "レッスン",
    speed_test: "速度テスト",
    games: "アーケード",
    settings: "環境設定",
    logs: "分析ログ",
    leaderboard: "ランキング",
    back_to_menu: "メニューへ戻る",

    // Dashboard metrics
    streak: "毎日の継続日数",
    coins: "獲得コイン",
    level: "レベル",
    xp: "現在の経験値 XP",
    best_wpm: "最高単語数 PB",
    rank: "パイロット資格",
    continue_lesson: "レッスンを再開",
    start_test: "テストを開始",
    welcome_pilot: "パイロット・ターミナル",
    weak_keys: "誤入力の多い弱点キー",
    correct_keys: "安定した得意キー",
    recent_activity: "最近の訓練履歴",

    // Settings
    identity_config: "パイロット身元設定",
    update_username: "ユーザー名更新",
    deep_synth: "キーボード・サウンド・シンセ",
    sound_status: "打鍵トーン発生器",
    sound_presets: "打鍵サウンドプリセット",
    volume: "打鍵音の音量設定",
    sound_enabled: "効果音を有効化",
    sound_disabled: "効果音をミュート",
    bgm_title: "フォーカスBGM環境音",
    bgm_enabled: "BGM 再生中",
    bgm_disabled: "BGM 消音",
    theme_selection: "テーマ外観＆アクセント",
    bright_mode: "ライトカラーUI",
    dark_mode: "サイバーパンク・ダークUI",
    primary_color: "アクセントカラーの選択",
    font_size_title: "タイピング文字サイズ調整",
    system_specs: "デバイス・エンジン仕様",
    reminder_title: "毎日の自動訓練通知リマインダー",
    reminder_time_label: "予約リマインダー時刻",
    test_push_btn: "プッシュテスト通知を起動",
    language_title: "インターフェース表示言語設定",
    specs_desc: "TypeMaster Pro v3.8 — 低遅延周波数発振機合成、高精度ローカルデータベース永続化、セキュアなプロキシ制御で実行中。",

    // Core Typing Actions
    current_passage: "選択されたタイピング課題",
    time_limit: "制限時間タイマー",
    sec_unit: "秒数",
    custom_time: "カスタム時間設定",
    start_run: "打鍵セッションに接続",
    speed: "入力速度",
    accuracy: "正確性",
    mistakes: "入力ミス",
    progress: "進捗割合",
    target: "ターゲット",
    xp_rewards: "取得した経験値",
    coins_gained: "獲得した報酬コイン",
    perfect_run: "パーフェクト正確性ボーナス獲得！",
    new_personal_best: "★ 自己ベスト目標をクリア！",
    results_summary: "タイピング分析パフォーマンス",
    try_again: "もう一度挑戦",

    // Arcade Game Screen
    falling_words: "フォーリング・プロダクト",
    space_shooter: "スペースコマンド・シューティング",
    arcade_play: "遊ぶ",
    arcade_high: "最高スコア",
    score: "現在の得点",
    game_over: "ゲームオーバー",
    wave: "ウェーブ数",
    coins_earned: "ゴールドコイン獲得枚数",
    start_game: "戦闘シミュレーション起動",
    type_to_shoot: "表示される単語を入力して敵機を迎撃せよ！"
  }
};
